services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: marong_db

    ports:
      - "3306:3306"
    volumes:
      - /Users/poom/IdeaProjects/BackEnd-Marong/marongDB.sql:/docker-entrypoint-initdb.d/marongDB.sql
    networks:
      - backend-marong

  springboot-app:
    image: springboot-app:latest  # Replace with your Spring Boot app image
    container_name: springboot-container
    build:
      context: .  # Dockerfile for Spring Boot should be in the same directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/marong_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
    networks:
      - backend-marong

networks:
  backend-marong:
    driver: bridge

